class Lookups:
    def __init__(self) -> None:
        self.Exposure_Pathway_Dictionary_Type = 1000
        self.Internalization_Dictionary_Type = 1001
        self.Mitigation_Dictionary_Type = 1002
        self.Mitigation_Exp_Insight_Type = 1003
        self.Mitigation_Int_Insight_Type = 1004



class InternalizationContextResolver:

    def __init__(self) -> None:

        self.Inclusion_Dictionary = {
            'AUDIT': ['AUDITED','AUDITORY','AUDITING','(UNAUDITED','AUDITORS','AUDITOR','UNAUDITED'],
            'BRIBE': ['ANTI-BRIBERY','BRIBERY'],
            'CHARGE': ['DISCHARGE','DISCHARGES','DISCHARGED','DISCHARGE-RELATED','CHARGED'],
            'CHARGES': ['DISCHARGES'],
            'CODE': ['(CODE','CODE-RELATED'],
            'COMPLIANCE': ['NONCOMPLIANCE','COMPLIANCE”'],
            'CONFLICT': ['CONFLICTING'] ,
            'CONTRACT': ['CONTRACTORS','CONTRACTOR','CONTRACTUAL','CONTRACTORS’','CONTRACTING','SUBCONTRACTORS','CONTRACTS/UNITS','CONTRACTS(A'],
            'CONTRACTS': ['CONTRACTS/UNITS','CONTRACTS(A'],
            'CORRUPT':['ANTI-CORRUPTION', 'CORRUPTION'],
            'DISCOUNT': ['DISCOUNTED','UNDISCOUNTED'],
            'EDUCATION': ['EDUCATIONAL','(EDUCATION'],
            'ETHICS': ['SECUREETHICSPOINTCOM/DOMAIN/MEDIA/EN/','ETHICALLY'],
            'ETHICAL': ['ETHICALLY'],
            'EXPENSE': ['EXPENSED','(EXPENSE','EXPENSED','(EXPENSE','EXPENSES(B'],
            'EXPENSES': ['EXPENSES(B'],
            'GOVERNANCE': ['GOVERNANCE1','GOVERNANCE—COMMITTEES','GOVERNANCE—COMPENSATION'],
            'GOVERNMENT': ['GOVERNMENT-LED','GOVERNMENTAL'],
            'IRS': ['(IRS'],
            'LAW': ['LAWMAKERS','LAWSUITS','LAWSUIT','LAWFUL','LAWFULLY','UNLAWFUL'],
            'LAWS': ['LAWSUITS','LAWSUIT'],
            'NATIONAL': ['INTERNATIONAL','NATIONALLY','NATIONALIZED','INTERNATIONALLY','NATIONALIZATION','“NATIONALLY'],
            'POLICY': ['POLICYMAKERS'],
            'REGULATION': ['CONSTRAINTS/REGULATIONS','REGULATIONS-PRIOR','REGULATIONS”','REGULATIONS—PRIOR'],
            'REGULATIONS': ['CONSTRAINTS/REGULATIONS','REGULATIONS-PRIOR','REGULATIONS”','REGULATIONS—PRIOR'],
            'RULE':['RULEMAKING','RULEMAKINGS','“RULE','RULE’S','RULE”'],
            'SAFETY': ['SAFETY-BASED','SAFETY-SENSITIVE','SAFETY-'],
            'TOLL': ['TOLL-FREE','TOLLING','(TOLL'],


            'CAPACITY': ['CAPACITY-'],
            'DISTRIBUTION': ['DISTRIBUTIONAB'],
            'FINANCIAL': ['NONFINANCIAL','FINANCIAL/BALANCE','NON-FINANCIAL'],
            'GLOBAL': ['GLOBALLY','(GLOBAL'],
            'MARKET': ['FREE-MARKET','MARKET-BASED','MARKETING','MARKETED','MARKET-COMPETITIVE','MARKETABILITY','MARKET-RELATED','REMARKET','MARK-TO-MARKET'],
            'OPERATIONS': ['OPERATIONS-FOCUSED','OPERATIONS-','OPERATIONS3','OPERATIONS4','PRESIDENT—OPERATIONS'],
            'PRODUCT': ['PRODUCTIVE','CO₂E/PRODUCTION','PRODUCTION','UNITS-OF-PRODUCTION','OF-PRODUCTION','NON-PRODUCTIVE','PER-UNIT-OF-PRODUCTION','OILPRODUCTIVE','PRODUCTION(C'],
            'PRODUCTION': ['CO₂E/PRODUCTION','UNITS-OF-PRODUCTION','OF-PRODUCTION','PER-UNIT-OF-PRODUCTION','PRODUCTION(C'],
            'SOCIAL': ['SOCIALLY'],
            'SUPPLIERS': ['SUPPLIERS’'],
            'SUPPLY': ['SUPPLY/'],
            'WEATHER': ['WEATHERIZATION','WEATHER-RELATED'],

            'DEMAND': ['ON-DEMAND'],
            'ENVIRONMENTAL': ['ENVIRONMENTALLY'],
            'HEALTH': ['HEALTHIER','HEALTHCARE','HEALTHY','(HEALTH'],
            'PORT': ['TRANSPORT','TRANSPORTS','TRANSPORTATION','TRANSPORTED','IMPORTED','EXPORTING','SUPPORT”','PORTFOLIO?'],
            'POWER': ['POWERFUL','POWERING','POWER-GENERATING','EMPOWER','EMPOWERING','EMPOWERED','POWERED'],
            'RAIL': ['RAILROAD','MOUNTRAIL'],
            'WATER': ['FRESHWATER','WATERSHEDS','(GROUNDWATER','GROUNDWATER','WATER/MILLION','SALTWATER','WASTEWATER','WATER-HANDLING','FRESH-WATER','WATER3','WATER-CONTROL','WATERSHED','WATER/DOMESTIC','FRESHWATER/DOMESTIC','WATERS','WATEROUS','PRICEWATERHOUSECOOPERS','/S/PRICEWATERHOUSECOOPERS','WATERFLOODING'],
            'CAPITAL': ['OVERCAPITALIZE','CAPITALIZATION','CAPITALIZED','DEBT-TO-CAPITAL'],
            'COST': ['LOW-COST','COST-EFFECTIVE','HIGHER-COST','COSTLY','(COSTS','COST-SHARING','(COST','COSTS(A','COSTS(B','COSTS(C'],
            'COSTS': ['(COSTS','COSTS(A','COSTS(B','COSTS(C'],
            'DEBT': ['DEBT-ADJUSTED','INDEBTEDNESS','DEBT-TO-CAPITAL'],
            'MAINTENANCE': ['MAINTENANCE-LEVEL'],
            'MATERIAL': ['MATERIALLY','MATERIALITY','IMMATERIAL'],
            'PORTS': ['TRANSPORTS'],
            'SECURITY': ['SECURITY-RELATED','SECURITY-','INSECURITY','CYBERSECURITY','“SECURITY'],
            'TAX': ['TAX-EXEMPT','TAXING','TAXABLE','PRETAX','PRE-TAX','TAX-RELATED','(PRETAX','TAXONOMY'],

            'ASSET': ['ASSET”','ASSETS”','ASSETS’','ASSETAB','ASSETS”', 'ASSETS’'],
            'BENEFIT': ['(BENEFIT','HTTPS//WWWMROBENEFITSCOM/','BENEFITING','BENEFITED','(BENEFITS'],
            'BENEFITS': ['HTTPS//WWWMROBENEFITSCOM/','(BENEFITS'],
            'BOOK': ['BOOKINGS','BOOKS','BOOKING'],
            'COMPETITIVE': ['COMPETITIVELY','COMPETITIVENESS','MARKET-COMPETITIVE'],
            'DIRECT': ['DIRECTLY','INDIRECT','INDIRECTLY','DIRECTED','(DIRECT'],
            'CONSUMER': ['CONSUMERS','CONSUMER-BASED','CONSUMERS','CONSUMERS’','CONSUMERS\''],
            'ENVIRONMENT': ['ENVIRONMENTAL','ENVIRONMENTALLY','MACRO-ENVIRONMENT','(ENVIRONMENT'],
            'HIRE': ['HIRES','HIRED'],
            'HUMAN': ['ANTI-HUMAN'],
            'IMPAIRMENT': ['(IMPAIRMENTS','IMPAIRMENTS'],
            'JOB': ['PRE-JOB','THE-JOB','JOBSITE','ON-THE-JOB','JOB-RELATED'],
            'JOBS': ['JOBSITE'],
            'OFFER': ['OFFERING','OFFERED','OFFERINGS'],
            'PERFORMANCE': ['PERFORMANCE1','PERFORMANCEA','NON-PERFORMANCE','NONPERFORMANCE','PERFORMANCE-BASED'],
            'RECOGNIZE': ['RECOGNIZED','RECOGNIZES','UNRECOGNIZED'],
            'RECRUIT': ['RECRUITING'],
            'RETAIN':  ['RETAINING','RETAINED','RETAINER'],
            'RISK': ['RISKS','RISK-BASED','RISK-TAKING','RISK-OWNER','LOW-RISK','HIGH-RISK','RISK-MITIGATION','HIGHER-RISK','RISK-ADJUSTED','RISK-WEIGHTED','CREDIT-ADJUSTED-RISK-FREE','RISK-FREE','RISK/RETURN'],
            'SEARCH':  ['RESEARCH'],
            'SERVICE': ['SHORT-SERVICE','SERVICE-BASED'],
            'STRESS': ['STRESS-TESTED','HIGH-STRESS','STRESS5','STRESS7','STRESS6','STRESSORS','STRESSED'],
            'TALENT':  ['TALENTED','TALENTS'],
            'TRAINING':  ['TRAININGS'],
            'DATA': ['DATABASE'],
            'EXPOSURE': ['EXPOSURES', 'EXPOSURES'],
            'LOCAL': ['LOCALLY','LOCALIZED','LOCAL-LEVEL'],
            'LOCATION': ['LOCATIONAL'] ,
            'LOSS': ['(LOSS','(LOSSES','GAINS/LOSSES','LOSS(A'],
            'LOSSES': ['(LOSSES','GAINS/LOSSES'],
            'ORDER': ['ORDERLY'],
            'OUTPUT': ['OUTPUTS'],
            'PATH': ['PATHWAY','PATHWAYS'],
            'SCENARIO':  ['SCENARIO”'],
            'SOLD': ['PRODUCED/REFINED/SOLD'],
            'STORE': ['RESTORE','STORED','RESTORED'],
            'SUPPLIER':  ['SUPPLIERS’', 'SUPPLIER’S'],
            'TRANSPORT':  ['TRANSPORTS','TRANSPORTATION','TRANSPORTED'],
            'TRUCK':  ['TRUCKLOADS','TRUCKERS'],
            'VALUE': ['VALUES','VALUED'],
            'VOLUME': ['HIGH-VOLUME','VOLUMETRIC','PRICE-VOLUME','PRICE/VOLUME','VOLUMETRIC-BASED'],
            'STRANDED':['“STRANDED','‘STRANDED'],
            'CONSTRAINED': ['CARBON-CONSTRAINED'],
            'LIMITED': ['LIMITED’S'],
            'NEW': ['NEWLY','“NEW'],
            'REVIEW': ['REVIEWED','REVIEWS','REVIEWING'],
            'STRUGGLE': ['STRUGGLED'],
            'TECHNOLOGY': ['TECHNOLOGY-DRIVEN'],
            'BEHAVIOR': ['BEHAVIORAL','BEHAVIOR-BASED'],
            'NEED': ['MUCH-NEEDED','NEEDED'],
            'PURCHASE': ['REPURCHASES','REPURCHASES.','PURCHASED','PURCHASER','PURCHASERS','REPURCHASE','REPURCHASED','PURCHASED(A'],
            'PURCHASES': ['REPURCHASES'],
            'QUALITY': ['HIGH-QUALITY'],
            'LEVERAGE': ['LEVERAGED'],
            'REPUTATION': ['REPUTATIONAL'],
            'TRADE': ['TRADEMARKS','TRADEMARK','TRADED','PUBLICLY-TRADED'],
            'PLANT': ['PLANT-'],
            'RATE': ['FIXED-RATE','FLOATING-RATE','RATE-OF-RETURN','RATE1'],
             'LEGAL': ['LEGALLY'],
             'LICENSE': ['LICENSED'] ,
             'NOTICE': ['ADVANCE-NOTICE'] ,
             'PERMIT': ['PERMITTING','RE-PERMITTING','PERMITTED'] ,
             'REPORTING': ['REPORTING”'],
             'RESOURCE': ['RESOURCES’'] ,
             'RESOURCES': ['RESOURCES’'] ,
             'STATE': ['(STATE','STATES’','STATES(A'],
             'STATES': ['STATES’','STATES(A'],
             'BREAK': ['OUTBREAKS','OUTBREAK'],
             'CLAIM': ['CLAIMING'],
             'SUGAR': ['SUGARLOAF'],
             'INCENTIVE': ['INCENTIVE-BASED'],
             'RETENTION': ['RETENTIONS'],
             'RETIREMENT': ['POSTRETIREMENT'],
            'GUIDELINE': ['GUIDELINES”'] ,
            'GUIDELINES': ['GUIDELINES”'] ,
            'PRICE': ['FIXED-PRICE','PRICE-VOLUME','PRICE/VOLUME','PRICES”','“PRICE'] ,
            'PRICES': ['PRICES”'] ,
            'PRICING': ['PRICING”'] ,
            'MINE': ['MINERAL','MINERALS'],
            'RESERVES': ['PRESERVES','RESERVES*','RESERVES”','PRESERVES','RESERVES*','RESERVES”'],
            'ACTUARY': ['ACTUARY’S'] ,
            'ASSESSMENT': ['REASSESSMENT'] ,
            'INSURED': ['UNINSURED','SELF-INSURED'] ,
            'PROGRESS': ['PROGRESSING','PROGRESSIVELY'] ,
            'EMPLOYMENT': ['POSTEMPLOYMENT'],
            'INFLATION': ['INFLATIONARY'],
            'BURDEN': ['BURDENED'],
            'EXPENDITURE': ['EXPENDITURES(A'],
            'EXPENDITURES': ['EXPENDITURES(A'],
            'OBLIGATION': ['OBLIGATIONS(D'],
            'OBLIGATIONS': ['OBLIGATIONS(D'],
            'PAY': ['PAYMENTS','PAYBACK','PAYMENT'],
            'DEVELOPMENT': ['DEVELOPMENTS'],
            'PERFORMANCE': ['PERFORMANCE1','PERFORMANCEA','NON-PERFORMANCE'],
            'EXECUTIVE ': ['EXECUTIVES','EXECUTIVE-LEVEL'] ,
            'STOCK ': ['FEEDSTOCK','STOCKHOLDERS’','STOCKHOLDERS'] ,
            'APPROACH': ['APPROACHES'] ,
            'DIVIDEND': ['DIVIDENDS'] ,
            'REINVESTMENT': ['(REINVESTMENT'] ,
            'PLAN': ['PLANS','PLANNING','PLANNED','“PLAN”'] ,
           
                       
        }

        self.Exclusion_Dictionary = {   
            'CONDUCT':['CONDUCTING', 'CONDUCTED', 'CONDUCTS','MISCONDUCT'],
            'IRS': ['CHAIRS','FIRST','PAIRS','RESERVOIRS','AFFAIRS','REPAIRS','FIRST-OF-MONTH','FIRST-DAY-OF-THE-','FIRST-DAY-OF-THE-MONTH'],
            'STATE': ['STATEMENT','STATEMENTS','STATE-OF-THE-ART','STATED','RESTATEMENTS','REINSTATE','STATEMENTS”','RESTATED','MISSTATEMENTS','MISSTATEMENT','ESTATE','STATEMENT”'],
            'PM': ['EQUIPMENT','DEVELOPMENT','DEVELOPMENTS','PPM','(PM25','JPMORGAN'],
            'PORT': ['REPORT','MARATHONOILCOM/SUSTAINABILITY-REPORT','SUPPORTED','REPORTING','REPORTS','IMPORTANCE','PORTFOLIO','SUPPORT','OPPORTUNITIES','OPPORTUNITY','SUPPORTING','IMPORTANT','SUPPORTS','REPORTED','PORTION','PROPORTIONAL','SUPPORTIVE','PROPORTION','PORTIONS','ESGREPORT@MARATHONOILCOM','SUPPORT”','PORTFOLIO?','REPORTABLE','FREEPORT-MCMORAN','OPPORTUNE','PROPORTIONATE','SUPPORTABLE','PORTFOLIOS','REPORTING”','“REPORT','REPORT”','“REPORT”','PORTION(B'],
            'RIVER': ['DRIVER','DRIVERS'],
            'RIVERS': ['DRIVERS'],
            'FEE': ['FEEL','FEEDBACK','FEEDSTOCK','FEET'],
            'INTEREST': ['INTERESTS','“INTERESTED','INTERESTED'],
            'RATE': ['NON-OPERATED','CORPORATE','INTEGRATED','OPERATED','DEMONSTRATE','DEMONSTRATES','CELEBRATED','STRATEGIC','OPERATE','STRATEGY','(CORPORATE','SEPARATE','INCORPORATE','INCORPORATES','TOLERATE','STRATEGIES','CONCENTRATED','GENERATE','DEMONSTRATED','ACCURATELY','INCORPORATED','OIL-OPERATED','GENERATED','OPERATES','TOP-RATED','INTEGRATE','RATEABCD','COLLABORATE','STRATEGICALLY','INACCURATE','ACCELERATED','NON-ACCELERATED','“ACCELERATED','SEPARATED','ACCELERATE','PRESIDENT—CORPORATE','CRATERING','DETERIORATE','DETERIORATES','ILLUSTRATES','CORROBORATED','COMMENSURATE','RATED','SEPARATELY','UNINCORPORATED','ACCURATE','“CORPORATE','INVESTORS—CORPORATE','ENUMERATED','—CORPORATE','PRORATED','HYDRATES','PENETRATED','GRATEFUL'],
            'RATES': ['DEMONSTRATES','INCORPORATES','OPERATES','DETERIORATES','ILLUSTRATES','HYDRATES'],
            'RENT': ['DIFFERENTIATED','CURRENT','DIFFERENT','TRANSPARENT','INHERENTLY','CURRENTLY','DETERRENTS','INHERENT','RENTALS','DIFFERENTLY','BRENT','DIFFERENTIALS','(CURRENTLY','NONCURRENT','DIFFERENTIAL','“DIFFERENTIALS”','PARENT'],
            'RENTS': ['DETERRENTS'],
            'PORTS': ['REPORTS','SUPPORTS'],
            'AGING': ['LEVERAGING','ENGAGING','MANAGING','ENCOURAGING','DISCOURAGING'],
            'AIR': ['CHAIRS','CHAIRMAN','CHAIR','FAIR','QUESTIONNAIRES','QUESTIONNAIRE','(IMPAIRMENTS','IMPAIRMENTS','IMPAIRMENT','REPAIR','PRAIRIE','PAIRS','PAIRING','IMPAIR','AFFAIRS','IMPAIRING','REPAIRS','FAIRLY','IMPAIRED','AIRCRAFT','CO-CHAIRMAN'],
            'ARM': ['WARMING','EARMARKED','ARMY','ARMED','HARM','HARMED','HARMFUL'],
            'BACK': ['FEEDBACK','BACKUP','PAYBACK','LEATHERBACK','FLOWBACK','BACKGROUNDS','BUYBACK','BACKGROUND','DIAMONDBACK'],
            'BILL': ['BILLIONS','BILLION','HAWKSBILL','BILLINGS','BILLING',],
            'BREAK': ['BREAKEVEN','BREAKTHROUGHS','BREAKTHROUGH','BREAKDOWN'],
            'DIRECT': ['DIRECTORS','DIRECTOR','DIRECTION','DIRECTORS”','“DIRECTOR','DIRECTORS—','DIRECTORS’','DIRECTOR’S','DIRECTORS—DIRECTOR'],
            'HEAD': ['WELLHEAD','AHEAD','HEAD-ON','HEADQUARTERS','WELLHEAD-','WHITEHEAD','OVERHEAD','WELLHEAD-ONLY'],
            'LEG': ['LEGAL','LEGISLATION','LEGISLATORS','DELEGATIONS','LEGISLATIVE','ALLEGING','ALLEGATIONS','COLLEGES','COLLEGE','ALLEGED','ALLEGE','LEGALLY','LEGACY'],
            'MENTAL': ['ENVIRONMENTAL','ENVIRONMENTALLY','FUNDAMENTALS','GOVERNMENTAL','SUPPLEMENTAL','FUNDAMENTAL','DETRIMENTALLY','INCREMENTAL'],
            'MIND': ['MINDSET'],
            'NECK': ['BOTTLENECKS'],
            'SKIN': ['ASKING'],
            'HR': ['THROUGH','THROUGHOUT','THREE','THREE-','BREAKTHROUGHS','THREATS','THREAT','CHRONIC','THREATENED','PASS-THROUGH','BREAKTHROUGH','THREE-DAY','THROUGHPUT','THREE-DIMENSIONAL','“THREE','THREE-WAY','THREE-YEAR','THRESHOLD','THRIVE'],
            'PTO': ['LAPTOPS','RAPTORS','LAPTOP'],
            'RAW':  ['WITHDRAWAL','WITHDRAWALS','WITHDRAWAL','WITHDRAWALS','WITHDRAWN','DRAW'],
            'LABOR': ['COLLABORATION','COLLABORATIVE','COLLABORATIVE”','COLLABORATE','COLLABORATING','LABORATORY'],
            'MINE': ['DETERMINE','DETERMINED','EXAMINE','PREDETERMINED','PROMINENTLY','DETERMINES','NOMINEES','NOMINEE','EXAMINED'],
            'MINES': ['DETERMINES'],
            'ENVIRONMENT': 'ENVIRONMENTS',

            'NEW': ['RENEWABLES','RENEWABLE','NEWBORNS','RENEWAL'],
            'QUALITY': ['EQUALITY'],
            'FINE': ['DEFINE','DEFINED','PRODUCED/REFINED/SOLD','REDEFINE','DEFINES'] ,
            'FINES': ['DEFINES'],
            'LAW': ['DELAWARE','BY-LAWS'] ,
            'LAWS': ['BY-LAWS'] ,
            'DEDUCTIBLE': ['NON-DEDUCTIBLE'],
            'PHYSICAL': ['GEOPHYSICAL'],
            'LOCATION': ['ALLOCATION', 'ALLOCATIONS'],
            'LOCATIONS': ['ALLOCATIONS'],
            'PRICE': ['PRICEWATERHOUSECOOPERS','/S/PRICEWATERHOUSECOOPERS'] ,
            'RESERVES': ['PRESERVES','PRESERVES'],
            'WEATHER': ['WEATHERFORD'] ,
            'AUDIT': ['AUDITORIUM'],
            'EARNINGS': ['LEARNINGS'],
            'VESTING': ['INVESTING'] ,
            'PLAN': ['PLANET','PLANT','EXPLANATION'] ,
        }
    
    def is_keyword_in_exclusion_list(self,keyword:str, related_word:str):

        try:

            related_words = self.Exclusion_Dictionary[keyword.upper()]

        except:
                return False

        if related_word.upper() in related_words:
            return True

        return False
    
    def is_keyword_in_inclusion_list(self,keyword:str, related_word:str):
        try:

            related_words = self.Inclusion_Dictionary[keyword.upper()]

        except:
                return False

        if related_word.upper() in related_words:
            return True

        return False
    


class ExposurePathwayContextResolver:

    def __init__(self) -> None:

        self.Inclusion_Dictionary = {
            'COMBAT': ['COMBATTING','COMBATS'],
            'FIRE': ['FIREFIGHTING'],
            'FOREST': ['RAINFOREST'],
            'PERIODIC': ['PERIODICALLY'],
            'PRESCRIBE': ['PRESCRIBED'],
            'RAIN': ['RAINFOREST'],
            'STORM': ['STORMS'],
            'HEAT': ['HEATERS'],
            'CREDIT': ['CREDITS'],
            'OFFSET': ['OFFSETS'],
            'DISTRIBUTION': ['DISTRIBUTIONS','DISTRIBUTIONAB'],
            'OPERATION': ['OPERATIONS','OPERATIONAL','OPERATIONS-FOCUSED','OPERATIONS-','OPERATIONALIZED','OPERATIONALLY','OPERATIONS3','OPERATIONS4'],
            'ENERGY': ['ENERGY-RELATED','NONENERGY'],
            'INVESTMENT': ['UNDER-INVESTMENT','(REINVESTMENT','REINVESTMENT','UNDERINVESTMENT','INVESTMENTS'],
            'PRODUCT ': ['PRODUCTION','CO₂E/PRODUCTION'],
            'RENEW': ['RENEWABLES'],
            'RENEWABLE': ['RENEWABLES'],
            'SHIFT': ['SHIFTED'],
            'ENERGY ': ['ENERGY-RELATED','NONENERGY'],
            'GAS': ['GAS/NATURAL','GASES','GAS-','GASKETS','GAS/TOTAL','GASOLINE'],
            'NATURAL': ['GAS/NATURAL'],
            'SAND': ['SANDS'],
            'CARBON': ['HYDROCARBONS','DECARBONIZATION','CARBON-CONSTRAINED','LOW-CARBON','HYDROCARBON','LOWER-CARBON'],
            'SYSTEM': ['SYSTEMIC','ECOSYSTEM','ECOSYSTEMS','SYSTEMATIC','MULTI-SYSTEM','SYSTEMS'],
            'SYSTEMS': ['ECOSYSTEMS'],
            'WATERSHED': ['WATERSHEDS'],
            'CULTURAL': ['CULTURALLY'],
            'PROGRAM': ['PROGRAM’S'],
            'SITE': ['WEBSITE','ONSITE','PRE-SITE','ON-SITE','JOBSITE','PARASITE','OFF-SITE'],
            'MPAS': ['ENCOMPASSING','ENCOMPASSES'],  
            'DISRUPT': ['DISRUPTION','DISRUPTIONS'],
            'DROUGHT': ['DROUGHTS'], 
            'LEAK': ['LEAKS'],
            'INVESTMENT': ['INVESTMENTS','UNDER-INVESTMENT','(REINVESTMENT','REINVESTMENT'],
            'SAVING': ['SAVINGS'],
            'CORRUPTION': ['ANTI-CORRUPTION'],
            'ECONOMY': ['ECONOMY-WIDE'],
            'SECURE': ['SECUREETHICSPOINTCOM/DOMAIN/MEDIA/EN/'],
            'COMMUNICATION': ['COMMUNICATIONS'],
            'FRAMEWORK': ['FRAMEWORKS'],
             'CHARGE': ['DISCHARGE','DISCHARGES','DISCHARGED','DISCHARGE-RELATED'],
             'CHARGES': ['DISCHARGES'], 
             'TAX': ['TAX-EXEMPT'], 
            'MAINTENANCE': ['MAINTENANCE-LEVEL'],
            'PRODUCTION': ['CO₂E/PRODUCTION'], 
            'SERVICE': ['SHORT-SERVICE'],
            'TECHNOLOGY': ['TECHNOLOGY-DRIVEN'],
            'TRAINING': ['TRAININGS'],
            'WATER': ['FRESHWATER','WATERSHEDS','(GROUNDWATER','GROUNDWATER','WATER/MILLION','SALTWATER','WASTEWATER','WATER-HANDLING','FRESH-WATER','WATER3','WATER-CONTROL','WATERSHED','WATER/DOMESTIC','FRESHWATER/DOMESTIC'],
            'EDUCATION': ['EDUCATIONAL','(EDUCATION'],
            'REGULATIONS': ['CONSTRAINTS/REGULATIONS'],
            'HEALTH': ['HEALTHIER','HEALTHCARE','HEALTHY','(HEALTH'],
            'SAFETY': ['SAFETY-BASED','SAFETY-SENSITIVE','SAFETY-'] ,
            'CAPACITY': ['CAPACITY-'] ,
            'DEMAND': ['ON-DEMAND'] ,
            'GOVERNANCE': ['GOVERNANCE1'],
            'SECURITY': ['SECURITY-RELATED','SECURITY-','INSECURITY','CYBERSECURITY'],
            'NATURAL ': ['GAS/NATURAL'],
            'BRIBE': ['ANTI-BRIBERY','BRIBERY'],
            '401': ['$401','401-1'],
            'BREAKTHROUGH': ['BREAKTHROUGHS'],
            'INVENT': ['INVENTORY'],
            'OUTPUT': ['OUTPUTS'],
            'PERFORMANCE': ['PERFORMANCE1','PERFORMANCEA','NON-PERFORMANCE','PRODUCTION','PRODUCTS','PRODUCTIVE','CO₂E/PRODUCTION'],
            'BENEFIT': ['(BENEFIT','HTTPS//WWWMROBENEFITSCOM/','BENEFITING','BENEFITED','(BENEFITS'],
            'BENEFITS': ['HTTPS//WWWMROBENEFITSCOM/','(BENEFITS'],
            'PAY': ['PAYMENTS','PAYBACK','PAYMENT'],
            'EXECUTIVE ': ['EXECUTIVES','EXECUTIVE-LEVEL'] ,
            'STOCK ': ['FEEDSTOCK','STOCKHOLDERS’','STOCKHOLDERS'] ,
            'REINVESTMENT': ['(REINVESTMENT'] ,
            'PRODUCT': ['PRODUCTION','PRODUCTS','PRODUCTIVE','CO₂E/PRODUCTION'] ,
            'DATA ': ['DATABASE'],
            'DEVELOPMENT': ['DEVELOPMENTS'],
             'APPROACH': ['APPROACHES'] ,
            'DIVIDEND': ['DIVIDENDS'] ,
            'REINVESTMENT': ['(REINVESTMENT'] ,
            'PLAN': ['PLANS','PLANNING','PLANNED','“PLAN”'] ,
            'EXTINGUISH': ['EXTINGUISHMENT'],
            'FLOODING': ['WATERFLOODING'],
            'PRESCRIBE': ['PRESCRIBES'],
            'SPREAD': ['WIDESPREAD','SPREADS'],
            'FLOOD': ['WATERFLOODING','FLOODING'],
            'CHARGE': ['CHARGED'],
            'CREDIT': ['CREDITWORTHINESS','“CREDIT','CREDITED','CREDIT-ADJUSTED-RISK-FREE','(“CREDIT','(CREDIT','(CREDITS','CREDITING','CREDITORS'],
            'OFFSET': ['OFFSETTING'],
            'PRICING': ['PRICING”'],
            'TAX': ['TAXING','TAXABLE','PRETAX','PRE-TAX','TAX-RELATED','(PRETAX','TAXONOMY'],
            'FUEL': ['FUELS'], 
            'OPERATION': ['PRESIDENT—OPERATIONS'], 
            'PRODUCTION': ['UNITS-OF-PRODUCTION','PER-UNIT-OF-PRODUCTION'],
            'MODERNIZATION': ['“MODERNIZATION'],
            'PRODUCT ': ['UNITS-OF-PRODUCTION','OF-PRODUCTION','NON-PRODUCTIVE','PER-UNIT-OF-PRODUCTION'],
            'RENEW': ['RENEWAL'],
            'SERVICE': ['SERVICE-BASED'], 
            'SHIFT': ['SHIFTS'],
            'COAL': ['COALBED','COALSEAM'],
            'NATURAL ': ['NATURALLY'],
            'OIL': ['MARATHONOILCOM/SUSTAINABILITY','OIL/CONDENSATE'],
            'WATER': ['WATERS','WATEROUS','WATERFLOODING'],
            'CARBON': ['HYDROCARBON-BEARING','CARBON-INTENSIVE'],
            'PROVISION': ['PROVISIONS','(PROVISION'], 
            'ART': ['EARTH','HEART','COUNTERPARTIES','PARTICULATE','CHARTERS','COUNTERPARTY','APART','PARTICIPANTS','PARTICIPANT','PARTY-OWNED','STARTING','PARTIAL','COUNTERPARTY’S','QUARTERS','PARTICIPATION”','ARTICLES','START','ARTIFICIAL','PARTICIPATES','ARTICLE'], 'NATURAL ': ['NATURALLY'],
            'NATURE ': ['NATURE-RELATED'],


        }

        self.Exclusion_Dictionary = {   
            'ICE': ['PRACTICES','SERVICES','SHORT-SERVICE','OFFICER','VICE','OFFICE','PRICE','OFFICES','OFFICERS','SERVICE','TWICE','PRICES','DEVICES','NOTICE','RETURN-TO-OFFICE','LICENSE','DEVICE','PRACTICE','JUSTICE'],
            'RAIN': ['TRAINING','CONSTRAIN','CARBON-CONSTRAINED','CONSTRAINTS','CONSTRAINTS/REGULATIONS','TRAIN','TRAINED','TRAININGS','TRAINED”','CONSTRAINED'],
            'PRODUCT ': ['PRODUCTIVE'],
            'COAL': ['COALITION'],
            'CORN': ['CORNERSTONE'],
            'OIL': ['MARATHONOILCOM/SUSTAINABILITY-REPORT','OIL’S','WWWMARATHONOILCOM','INTEGRITY@MARATHONOILCOM','OIL-OPERATED','OILFIELD','OIL-SPECIFIC','OIL”','(OIL','(NON-OIL','NON-OIL','ESGREPORT@MARATHONOILCOM','WWWMARATHONOIL'],
            'ORE': ['CORE','MORE','UNDERSCORE','SCORECARD','SCORECARDS','THEREFORE','FOREIGN','FORENSICS','OFFSHORE','MOREOVER','FORECASTS','FORECASTING','EXPLORES','FORECAST','UNDERSCORES','AFOREMENTIONED','FORESEEABLE','FORESTS','DEFORESTATION','FOREST','RAINFOREST','RESTORE','BEFORE','ONSHORE','STORES','STORED','TAILORED','EXPLORE','RESTORED','“FORECAST”'],
            'ORES': ['EXPLORES','UNDERSCORES','FORESEEABLE','FORESTS','DEFORESTATION','FOREST','RAINFOREST','STORES'],
            'RICE ': ['PRICE','PRICES'],
            'SAND': ['THOUSANDS','THOUSAND'],
            'STONE': ['CORNERSTONE'],
            'FOREST': ['DEFORESTATION','RAINFOREST'],
            'ART': ['PARTY','PARTICULARLY','PARTNERS','PART','PARTNERSHIPS','PARTICIPATION','CHARTS','CHARTER','QUARTERLY','PARTIES','PARTISAN','PARTICIPATE','PARTNER','PARTICIPATED','SMART','QUARTER','THIRD-PARTY','CHART','PARTICULAR','PARTICIPATING','EARTH’S','PARTNERSHIP','EARTHQUAKES','THIRD-PARTY-LED','PARTNERED','STATE-OF-THE-ART','DEPARTMENTS','HEADQUARTERS','STARTED','DEPARTMENT','SUBPART','PARTIALLY'],
            'ARTS': ['CHARTS'],
            'CULTURAL': ['AGRICULTURAL'],
            'PH': ['PHILOSOPHY','GRAPHIC','PHYSICAL','PHONES','SOPHISTICATION','PHASE','UPHOLD','ATMOSPHERE','PHOTO','ELEPHANTS','PHASES','GEOGRAPHIC','PHONE','EMPHASIS','ORPHAN'],
            'FEE': ['FEEL','FEEDBACK','FEEDSTOCK','FEET'],
            'EARNINGS': ['LEARNINGS'],
            'VESTING': ['INVESTING'] ,
            'PLAN': ['PLANET','PLANT','EXPLANATION'] ,
            'FISH': ['KINGFISHER'],
            'ICE': ['LICENSES','FIXED-PRICE','NOTICES','PRICE-VOLUME','INDICES','PRICE/VOLUME','PRICEWATERHOUSECOOPERS','INVOICED','SERVICE-BASED','NON-OFFICER','NON-OFFICERS','LICENSED','ADVANCE-NOTICE','/S/PRICEWATERHOUSECOOPERS','PRICES”','“PRICE'],
            'RAIN': ['ENGRAINED','UKRAINE','STRAIN','STRAINS'],
            'CREDIT': ['ACCREDITATION'],
            'ORE': ['UNFORESEEN','WELLBORE','FURTHERMORE','FOREGOING','FORECASTED','VALOREM','FAVORED','MONITORED','NON-CORE','BORE','AUTHORED','CO-AUTHORED','SPONSORED','EXPLORER'],
            'ORES': ['UNFORESEEN'], 
            'RICE ': ['FIXED-PRICE','PRICE-VOLUME','PRICE/VOLUME','PRICEWATERHOUSECOOPERS','/S/PRICEWATERHOUSECOOPERS','PRICES”','“PRICE'],
            'STONE': ['MILESTONES'], 
            'WATER': ['PRICEWATERHOUSECOOPERS','/S/PRICEWATERHOUSECOOPERS'],
            'WOOD': ['WOODFORD'] ,
            'TREE': ['STREET'] ,
            'NATURE ': ['SIGNATURES','SIGNATURE'] ,
            'SITE': ['REQUISITE'] ,


        }
    
    def is_keyword_in_exclusion_list(self,keyword:str, related_word:str):

        try:

            related_words = self.Exclusion_Dictionary[keyword.upper()]

        except:
                return False

        if related_word.upper() in related_words:
            return True

        return False
    
    def is_keyword_in_inclusion_list(self,keyword:str, related_word:str):
        try:

            related_words = self.Inclusion_Dictionary[keyword.upper()]

        except:
                return False

        if related_word.upper() in related_words:
            return True

        return False
    
