# Cloud Build configuration for Cloud Run deployment
steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--build-arg'
      - 'BUILD_ID=${BUILD_ID}'
      - '--build-arg'
      - 'BUILD_DATE=${_BUILD_DATE}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/avisk-core-services:${BUILD_ID}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/avisk-core-services:latest'
      - '.'

  # Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - '--all-tags'
      - 'gcr.io/${PROJECT_ID}/avisk-core-services'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'avisk-core-services-${_ENVIRONMENT}'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/avisk-core-services:${BUILD_ID}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '1'
      - '--timeout'
      - '3600'
      - '--add-cloudsql-instances'
      - 'avisk-ai-platform:us-central1:avisk-core-dev'
      - '--set-env-vars'
      - 'ENVIRONMENT=cloud,DEPLOYMENT_ENV=${_ENVIRONMENT},GCS_BUCKET_DEVELOPMENT=avisk-app-data-eb7773c8,GCS_BUCKET_TEST=avisk-app-data-eb7773c8,GCS_BUCKET_PRODUCTION=avisk-app-data-eb7773c8,USE_GCS=true,BUILD_ID=${BUILD_ID},BUILD_DATE=${_BUILD_DATE}'

# Build substitutions
substitutions:
  _ENVIRONMENT: 'development'
  _REGION: 'us-central1'
  _BUILD_DATE: '${_BUILD_DATE}'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  
timeout: '2400s'

images:
  - 'gcr.io/${PROJECT_ID}/avisk-core-services:${BUILD_ID}'
  - 'gcr.io/${PROJECT_ID}/avisk-core-services:latest'